samples_file: "config/samples.tsv"
genome_fasta: "testdata/genome/genome.fna"
gtf: "testdata/genome/genes.gtf"



# parametros adicionales

# Reporte global 
multiqc_comment: "Este es un reporte de prueba con un subset de datos."
