samples_file: "config/samples.tsv"
genome_fasta: "testdata/genome/s288c_genome_ncbi.fna"
gtf: "testdata/genome/s288c_genome_ncbi.gtf"
gtf_quant: "testdata/genome/s288c_genome_ncbi_stringtie.gtf"



# parametros adicionales

# Reporte global 
multiqc_comment: "Los datos para este muestra provienen del artículo A comprehensive comparison of RNA-Seq-based transcriptome analysis from reads to differential gene expression and cross-comparison with microarrays: a case study in Saccharomyces cerevisiae de Nookaew et al., en el cual se estudia la cepa de S. cerevisiae CEN.PK 113-7D (levadura) bajo dos condiciones metabólicas distintas: exceso de glucosa (batch) y limitación de glucosa (chemostat)."
