# Configuración personalizada para MultiQC
# Configurar el logotipo personalizado
#custom_logo: "./config/logo.png"  # Ruta al archivo del logo (puede ser relativa o absoluta)
#custom_logo_url: "https://github.com/trippv/integrity_massively"  # URL opcional a la que enlazará el logo

intro_text: "REPORTE DE MUESTRA"




# Información del encabezado del informe
report_header_info:
  - Nombre: "Thalassomics"
  - Contacto: "info@thalassomics.com"
  - Sitio Web: "https://thalassomics.com"
  - Tipo de proyecto: "RNA-seq"
  - Platafora: "HiSeq 2500 High Output V4"
  - Setup: "2x125"



# Opcional: Configuración adicional para personalizar el informe
show_analysis_paths: False  # No mostrar rutas de archivos en el informe
show_analysis_time: False   # Mostrar la fecha y hora del análisis
disable_version_detection: false
skip_versions_section: false


# Se utilizan modulos personalizados para mostrar la información en español. 
# Los modulos personalizados se encuentran en ~/mi_multiqc_pkg


# se excluyen modulos no deseados para usar los personalizados
exclude_modules:
  - fastp
  - rseqc


# orden de los modulos
#top_modules:
#  - mi_fastp:
#      info: "Análisis de calidad de lecturas con Fastp"
#      extra: "Este módulo analiza la calidad de las lecturas utilizando Fastp, proporcionando estadísticas detalladas sobre la calidad de las secuencias."
#  - samtools:
#      info: "Análisis de archivos BAM con Samtools"
#      extra: "Este módulo utiliza Samtools para analizar archivos BAM, proporcionando estadísticas sobre la alineación y cobertura de las lecturas."
#  - bowtie2:
#      info: "Alineamiento de lecturas con Bowtie2"
#      extra: "Este módulo utiliza Bowtie2 para alinear las lecturas a un genoma de referencia, proporcionando estadísticas sobre el alineamiento."
#  - gffcompare
#  - distance
#  - mqc_pca_scatter_plot
#  - mqc_volcano_plot
#  - mqc_abundance_heatmap
#
#

# --- Personalización de Columnas de la Tabla General Statistics ---
# ---- SOlo mostrar resultados de fastp. Ocultar alineamientos ---
table_columns_visible:
  mi_fastp:
    mi_fastp-after_filtering_q30_rate: True
    mi_fastp-filtering_result_passed_filter_reads: True
    mi_fastp-after_filtering_gc_content: True
    mi_fastp-pct_surviving: True
    mi_fastp-pct_adapter: True
    mi_fastp-pct_duplication: True
  samtools_stats-error_rate: False
  samtools_stats-non_primary_alignments: False
  samtools_stats-reads_mapped: False
  samtools_stats-reads_mapped_percent: False
  samtools_stats-reads_properly_paired_percent: False
  samtools_stats-raw_total_sequences: False
  bowtie_2_hisat2-overall_alignment_rate: False





# Agrega la matriz de distancia como un módulo personalizado
custom_data:
    distance:
      id: 'distance'
      section_name: 'Matriz de distancia'
      plot_type: 'heatmap'
      file_format: 'txt'
      pconfig:
        id: 'distancia_heatmap'
      cluster_cols: true
      sort_rows: true
      legend: 'abundancia'
      colorscale: 'viridis'

sp:
  distance:
    fn: '*distance_matrix.txt'
  mi_fastp:
    fn: "*_fastp.json"

  mi_rseqc/read_distribution:
      fn: "*.read_distribution.txt"
  mi_rseqc/read_duplication_pos:
    fn: "*.pos.DupRate.xls"
  mi_rseqc/inner_distance:
    fn: "*.inner_distance_freq.txt"
  mi_rseqc/gene_body_coverage:
    fn: "*.geneBodyCoverage.txt"
  mi_bowtie2:
    contents: "overall alignment rate" # Bowtie2 se reconoce mejor por esta frase
    # Si tus logs tienen una extensión fija, añádela para que sea más rápido:
    # fn: "*.bowtie2.log"
