executor: slurm
use-conda: true
jobs: 1                      # Máximo de jobs en paralelo (ajusta según tu cluster)
latency-wait: 2           # Espera en segundos para que aparezcan archivos de salida
retries: 2                  # Número de reintentos si falla una regla

default-resources:
  threads: 4                     # Valor por defecto si una regla no lo especifica
  mem_mb: attempt * 4000         # 4GB por hilo como punto de partida
  runtime: 8640                  # en minutos (6 días)
  slurm_partition: cicese       # cicese o d30
  slurm_account: clarissa
